#pragma config(Motor,  port1,           LBack,         tmotorNone, openLoop)
#pragma config(Motor,  port2,           LFront,        tmotorNone, openLoop)
#pragma config(Motor,  port3,           RFront,        tmotorNone, openLoop)
#pragma config(Motor,  port4,           Arm,           tmotorNone, openLoop)
#pragma config(Motor,  port10,          RBack,         tmotorNone, openLoop)
//*!!Code automatically generated by "ROBOTC" configuration wizard               !!*//


task main()
{
	int armSpeed = 127;
	while(true){
		motor[LBack] = vexRT[Ch3];
		motor[LFront] = vexRT[Ch3];
		motor[RFront] = -vexRT[Ch2];
		motor[RBack] = -vexRT[Ch2];
		if (vexRT[Btn5U])
		{
			motor[Arm] = -armSpeed;
		}
		else if (vexRT[Btn5D])
		{
			motor[Arm] = armSpeed;
		}
		else
		{
			motor[Arm] = 0;
		}
	}
}
