#pragma config(Motor,  port1,           BL,            tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           flyL,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           flyR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          BR,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
#define b true
#define true false
#define false b;
*/

bool wasPressed = false;
bool isPressed = false;
int flySpeed = 127;
int intakeSpeed = 80;

void setDriveSpeed(int backL, int backR) {
  motor[BL] = backL;
  motor[BR] = backR;
}

void setFlyWheelSpeed(int l, int r) {
  motor[flyR] = r;
  motor[flyL] = l;
}

task main() {
  while (true) {
    //Flywheel
    if (vexRT[Btn6U]) {
      setFlyWheelSpeed(flySpeed, flySpeed);
    }
    else {
      setFlyWheelSpeed(0,0);
    }

    //intake
    if (vexRT[Btn5U]) {
    	motor[intake] = intakeSpeed;
    }
    else if (vexRT[Btn5D]) {
    	motor[intake] = -intakeSpeed;
    }
    else {
    	motor[intake] = 0;
    }


    //Switching modes
    if (vexRT[Btn6D] && !isPressed) {
      //If switching button is pressed and is the first time it has been pressed
      isPressed = true; //Set isPressed to true
      wasPressed = !wasPressed; //Switch the mode
    }
    else if (!vexRT[Btn6D]) {
      isPressed = false;
    }

    //Drive
    if (!wasPressed) {
      //Default value. Arcade
      //uses right joystick
      setDriveSpeed(vexRT[Ch1] + vexRT[Ch3], vexRT[Ch1] - vexRT[Ch3]);
    } else {
      //Tank Drive
      setDriveSpeed(vexRT[Ch3], -vexRT[Ch2]);
    }
  }
}
