#pragma config(Sensor, dgtl1, armLimiter, sensorTouch)
#pragma config(Motor, port1, BL, tmotorVex393_HBridge, openLoop)
#pragma config(Motor, port2, BR, tmotorVex393_MC29, openLoop)
#pragma config(Motor, port8, Arm, tmotorVex393_MC29, openLoop)
#pragma config(Motor, port9, FR, tmotorVex393_MC29, openLoop)
#pragma config(Motor, port10, FL, tmotorVex393_HBridge, openLoop)
  //*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool wasPressed = false;
bool isPressed = false;
int armSpeed = 80;

void setDriveSpeed(int frontL, int frontR, int backL, int backR) {
  motor[FL] = frontL;
  motor[FR] = frontR;
  motor[BL] = backL;
  motor[BR] = backR;
}

task main() {
  while (true) {
    //Arm
    if (vexRT[Btn5U]) {
      motor[Arm] = armSpeed;
    }
    else if (vexRT[Btn5D] && !SensorValue[armLimiter]) {
      //When 5D is pressed and the sensor is not triggered, allow movement
      motor[Arm] = -1 * armSpeed;
    }
    else {
      motor[Arm] = 0;
    }

    //Switching modes
    if (vexRT[Btn6U] && !isPressed) {
      //If switching button is pressed and is the first time it has been pressed
      isPressed = true; //Set isPressed to true
      wasPressed = !wasPressed; //Switch the mode
    }
    else if (!vexRT[Btn6U]) {
      isPressed = false;
    }

    //Drive
    if (!wasPressed) {
      //Default value. Arcade
      //uses right joystick
      setDriveSpeed(vexRT[Ch1] + vexRT[Ch3], vexRT[Ch1] - vexRT[Ch3], vexRT[Ch1] + vexRT[Ch3], vexRT[Ch1] - vexRT[Ch3]);
      // motor[BL] = vexRT[Ch1] + vexRT[Ch3];
      // motor[FL] = vexRT[Ch1] + vexRT[Ch3];
      // motor[BR] = vexRT[Ch1] - vexRT[Ch3];
      // motor[FR] = vexRT[Ch1] - vexRT[Ch3];
    } else {
      //Tank Drive
      setDriveSpeed(vexRT[Ch3], -vexRT[Ch2], vexRT[Ch3], -vexRT[Ch2]);
      // motor[BL] = vexRT[Ch3];
      // motor[FL] = vexRT[Ch3];
      // motor[BR] = vexRT[Ch1];
      // motor[FR] = vexRT[Ch1];
    }
  }
}
