#pragma config(Motor,  port1,           fl,            tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           fr,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           br,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          bl,            tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Message to Max:
Go to Robot->Platform Type, Robot->Platform Type->VEX Robotics, ensure both are set to Vex 2.0 Cortex
Go to Robot->Motors and Sensors setup. Click the 'reverse' checkbox for the claw and intakeR motors if they are reversed
Go to line 87 to set the speed. It can be between 0 and 127.
*/


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void drive(int l, int r) {
	motor[fl] = motor[bl] = l;
	motor[fr] = motor[br] = r;
}


task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  drive(70, 70);
  wait1Msec(2000);
  drive(0,0);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



const int clawSpeed = 127;
const int armSpeed = 60;

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
  	drive(vexRT[Ch3], vexRT[Ch2]);

   	if (vexRT[Btn5U]) motor[arm] = 40;
   	else if (vexRT[Btn5D]) motor[arm] = -80;
   	else motor[arm] = 0;

   	if (vexRT[Btn6U]) motor[claw] = clawSpeed;
   	else if (vexRT[Btn6D]) motor[claw] = -clawSpeed;
   	else motor[claw] = 0;

  }
}
