#pragma config(Motor,  port1,           r,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,           claw,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           arm,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          l,             tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int armSpeed = 50;
const int slowClawSpeed = 50;
const int clawSpeed = 100;
task main()
{
	while(true)
	{
		motor[r] = vexRT[Ch2];
		motor[l] = vexRT[Ch3];

		motor[r] =
		/*
		if (vexRT[Btn5D]) motor[arm] = -armSpeed;
		else if (vexRT[Btn5U]) motor[arm] = armSpeed;
		else motor[arm] = 0;*/

		if (vexRT[Btn6D] && vexRT[Btn6U]) motor[claw] = slowClawSpeed;
		else if (vexRT[Btn6D]) motor[claw] = -clawSpeed;
		else if (vexRT[Btn6U]) motor[claw] = clawSpeed;
		else motor[claw] = 0;
	}
}
