#pragma config(Motor,  port1,           driveL,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           armL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intake,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           armR,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          driveR,        tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

const int armSpeed = 100;
const int intakeSpeed = 127;


void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;


	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void driveStraight(int speed) {
	motor[driveL] = motor[driveR] = speed;
}

void armUp(int speed) {
	motor[armR] = motor[armL] = speed;
}


task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
	//Arm up, drive forward, intake, drive back

	armUp(-60);
	wait1Msec(500);
	armUp(0);
	driveStraight(70);
	wait1Msec(1500);
	driveStraight(0);
  motor[intake] = intakeSpeed; //Push the balls out
  wait1Msec(3000);
  driveStraight(-70);
  wait1Msec(2000);
  driveStraight(0);
  motor[intake] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/




task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
  	motor[driveR] = vexRT[Ch2];
  	motor[driveL] = vexRT[Ch3];


  	if (vexRT[Btn5D]) armUp(-armSpeed);
		else if (vexRT[Btn5U]) armUp(armSpeed);
		else armUp(0);

  	if (vexRT[Btn6D]) motor[intake] = intakeSpeed;
		else if (vexRT[Btn6U]) motor[intake] = -intakeSpeed;
		else motor[intake] = 0;
  }
}
