#pragma config(Sensor, dgtl1,  armBottom,      sensorTouch)
#pragma config(Sensor, dgtl2,  armTop,         sensorTouch)
#pragma config(Motor,  port1,           BL,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           armL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           claw,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           armR,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BR,            tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



int setMinSpeed(int min, int val) {
	if (abs(val) > min) {
		return val;
	}
	else {
		return 0;
	}
}

void drive(int left, int right) {
	int min = 5;
	motor[BL] = motor[FL] = setMinSpeed(min, left);
	motor[BR] = motor[FR] = setMinSpeed(min, right);
}


void setArmSpeed(int speed) {
	motor[armL] = motor[armR] = speed;
}


int armSpeed = 80;
int clawSpeed = 60;

task main() {

	while(true) {
		drive(vexRT[Ch3] + vexRT[Ch1], vexRT[Ch3] - vexRT[Ch1]);

		//Arm
		if (vexRT[Btn5D] && !SensorValue[armBottom]) {
			setArmSpeed(armSpeed);
		}
		else if (vexRT[Btn5U] && !SensorValue[armTop]) {
			setArmSpeed(-armSpeed);
		}
		else {
			setArmSpeed(0);
		}

		//Claw
		if (vexRT[Btn6U]) {
			motor[claw] = clawSpeed;
		}
		else if (vexRT[Btn6D]) {
			motor[claw] = -clawSpeed;
		}
		else {
			motor[claw] = 0;
		}
	}
}
