#pragma config(Motor,  port1,           backLeft,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           armLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mobileLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mobileRight,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           armRight,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          backRight,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


const int armSpeed = 60;
//-127 to 127
task main() {
	while (true) {
		motor[backleft] = motor[frontLeft] = vexRT[Ch3];
		motor[backRight] = motor[frontRight] = vexRT[Ch1];

		if (vexRT[Btn5U]) {
			motor[armLeft] = motor[armRight] = armSpeed;
		}
		else if (vexRT[Btn5D]) {
			motor[armLeft] = motor[armRight] = -armSpeed;
		}
		else {
			motor[armLeft] = motor[armRight] = 0;
		}



		wait1Msec(1);
	}
}
