#pragma config(Sensor, I2C_1,  quad,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port3,           armLeft,       tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           armRight,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
double integral = 0;
float kP = 0.5;
float kI = 0.01;
float kD = 0.01;

int target = -696;

int prevError = 0;

task main()
{
while(true) {
	int error = target - nMotorEncoder[armLeft];
  integral += error;

  int deltaError = error - prevError;
  prevError = error;


  int power = error * kP + integral * kI + deltaError * kD;
	motor[armLeft] = motor[armRight] = power;


	writeDebugStreamLine("Motor: %d Sensor: %d Error: %d dt: %d Integral %d",power, nMotorEncoder[armLeft], error, deltaError, integral);
	wait1Msec(100);
}
}
