#pragma config(Motor,  port1,           driveLFront,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveLBack,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           armL,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           armR,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           driveRBack,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          driveRFront,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


bool driveIsTank = true;
bool driveWasPressed = false;
int armSpeed = 100;
int armStall = 35; //stall speed to keep arm in place


void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

void drive(int l, int r) {
		motor[driveLFront] = motor[driveLBack] = l;
		motor[driveRFront] = motor[driveRBack] = r;
}

void moveArm(int speed)
{
	motor[armL] = motor[armR] = speed;
}



task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
}



task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
  	if (vexRT[Btn8D] && !driveWasPressed) {
  			//pressing 8D switches drive mode
				driveIsTank = !driveIsTank;
				driveWasPressed = true;
  	}

  	else {
  		//prevents drive mode from constantly changing
  		driveWasPressed = false;
  	}


  	if (driveIsTank) {
  		//tank drive -> drives each side individually
  		drive(vexRT[Ch3], vexRT[Ch2]);
  	}
  	else {
  		//arcade drive -> left joystick for forward/back, right joystick for left/right
  		drive(vexRT[Ch3] + vexRT[Ch1], vexRT[Ch3] - vexRT[Ch1]);
  	}
  	if (vexRT[Btn5U] && vexRT[Btn5D])
  	{
  		//pressing 5U and 5D stalls arm in place
  		moveArm(armStall);
  	}
  	else if (vexRT[Btn5U])
  	{
  		//pressing 5U moves arm up
  		moveArm(armSpeed);
  	}
  	else if (vexRT[Btn5D])
  	{
  		//pressing 5D moves arm down
  		moveArm(-armSpeed);
  	}
  	else
  	{
  		//otherwise do nothing
  		moveArm(0);
  	}
	}
}
