#pragma config(Motor,  port1,           driveFR,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           driveFL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           driveBL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          driveBR,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setMotorSpeed(bool frontOrBack, int left, int right) {
	if (frontOrBack) {
		motor[driveFR] = -right;
		motor[driveFL] = -left;
	}

	else {
		motor[driveBR] = left;
		motor[driveBL] = right;
	}
}

task main() {
	bool mode = true;
	//true is speed/frontDrive
	bool speedAndTorque = false;

	bool wasPressed = false;
	while (true) {
		if (vexRT[Btn5U]){
			speedAndTorque = !speedAndTorque;
			setMotorSpeed(mode,0,0);
			setMotorSpeed(!mode,0,0);
		}
		if (vexRT[Btn6U] && !wasPressed) {
			//If button pressed and was not pressed before, change mode, set wasPressed to true
			setMotorSpeed(mode,0,0);//set the motor speed to zero
			mode = !mode;
			wasPressed = true;
		}
		else if (wasPressed) {
			//If wasPressed is true but is not pressed any more, change value to false
			wasPressed = false;
		}

		if (speedAndTorque) {
			setMotorSpeed(mode, vexRT[Ch3], vexRT[Ch2]);
			setMotorSpeed(!mode, -vexRT[Ch3], -vexRT[Ch2]);
		}
		else {
			setMotorSpeed(mode, vexRT[Ch3], vexRT[Ch2]);
		}
	}
}
