#pragma config(Motor,  port2,           DriveFL,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           DriveFR,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           DriveBL,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           DriveBR,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//ALSO TEST IF CHANGING THE 100 to 127 CHANGES MAX SPEED
//I.E. CHANGE TO (1/127)...
short absolute(short blabla) {
	if (blabla < 0) {
		blabla = blabla * -1;
	}
	return blabla;
}

short exponential(short channel) {
  return (100/(127^2)) * vexRT[channel] * absolute(vexRT[channel]);
}


/*
task main() {
	while (true) {
		short channelOne   = ((1 / 127) * vexRT[Ch1] * absolute(vexRT[Ch1]));
		short channelThree = ((1 / 127) * vexRT[Ch3] * absolute(vexRT[Ch3]));
		short channelFour = ((1 / 127) * vexRT[Ch4] * absolute(vexRT[Ch4]))
		motor[driveFL] =  channelThree + channelFour + channelOne;
		motor[driveFR] = -channelThree + channelFour + channelOne;
		motor[driveBL] =  channelThree - channelFour + channelOne;
		motor[driveBR] = -channelThree - channelFour + channelOne;
	}
}

Code explanation:
(100/127*127) * (channel*abs(channel));

Motor max value may OE may not be 100, while controller max is definitely 127.

The 100/127 squared divides max motor value by 127 squared so that when the controller is at 127,
the motor value is 100.

The abs stands for absolute, meaning it is always positive,
while the other one can be positive and negative so it can reverse.

By squaring, the growth is exponential.
*/
task main() {
	while(true){
		motor[DriveFL] = exponential(Ch3) + exponential(Ch4) + exponential(Ch1);
		motor[DriveFR] = -exponential(Ch3) + exponential(Ch4) + exponential(Ch1);
		motor[DriveBL] = exponential(Ch3) - exponential(Ch4) + exponential(Ch1);
		motor[DriveBR] = -exponential(Ch3) -exponential(Ch4) + exponential(Ch1);
	}
}
