#pragma config(Sensor, in1,    potentArm,      sensorPotentiometer)
#pragma config(Sensor, in2,    potentWrist,      sensorPotentiometer)

#pragma config(Motor,  port2,           driveMotorRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           armLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           wristLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           driveCenter,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           wristRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           armRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           driveMotorLeft,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setArmSpeed(int speed, int increment) {
	if (increment == 1) {
		//If increment is set to true, add to it instead of setting it
		motor[armRight] += speed;
		motor[armLeft]  += speed;
	}
	else {
		motor[armRight] = speed;
		motor[armLeft]  = speed;
	}
}


void setWristSpeed(int speed, int increment) {
	//The same as setArmSpeed
	if (increment == 1) {
		motor[wristRight] += speed;
		motor[wristLeft]  += speed;
	}
	else {
		motor[wristRight] = speed;
		motor[wristLeft]  = speed;
	}
}


int stabilize(int current, int before) {
	int difference = current - before;
	//Difference is the change between in arm angle
	//Positive means it is above the previous angle
	//Negative means it is below the previous angle

	if (difference < 0) {
		//Smaller than 0: Down?????????
		//THIS MAY BE THE WRONG WAY ROUND!!!!!
		//return -1;
		return 1;//Changed from -1. If it breaks, delete this
	}
	else if (difference > 0) {
		//Bigger than 0; 
		//return 1;
		return -1;
	}
	else {
		//Has not changed
		return 0;
	}
}

int stabilizeKevin(int current, int before) {//Taken from KevBoy's code and edited
	int maxIncrement = 10;
	int speed = current - before;
	int increment = (speed > 0)? log(speed) * maxIncrement: log(-speed) * -maxIncrement;
	//If positive, make increment the log of speed * max. Else, make it the -ve log * -ve max
	//int increment = log(speed) * maxIncrement;
	increment = (increment > maxIncrement)? maxIncrement: increment;
	//If greater than the max, make it the max
	// if (increment > maxIncrement) {
	// 	increment = maxIncrement;
	// }
	//increment *= direction;
	return increment;
}



task armControl() {
	//Call it in task main() with StartTask(armControl);
	//STop with EndTask(armControl);
	int interval = 50;//How often the stabilization runs (in milliseconds) 
	int incrementationSpeed = 1;//How much to increase the arm speed by
	int armSpeed = 127;//Speed to set the arm motors to go


	//Initialization of current and before sensor values
	int beforePotentArmValue = SensorValue[potentArm];
	int currentPotentArmValue = SensorValue[potentArm];

	while (true) {
		wait1Msec(interval);
		//Wait a set amount of time

		beforePotentArmValue = currentPotentArmValue;
		currentPotentArmValue = SensorValue[potentArm];
		//Changes both values. DO NOT CHANGE THE ORDER THIS IS HAPPENING

		//LINEAR
		setArmSpeed(stabilize(currentPotentArmValue, beforePotentArmValue) * incrementationSpeed, 1);
		//Tells it if it needs to go up or down, multiplies it to change speed faster, and the 1 to increment instead of set

		//LOGARTHMIC
		setArmSpeed(stabilizeKevin(currentPotentArmValue, beforePotentArmValue), 1);
		//

	}
}

task main() {
	int wristSpeed = 60;
	bool armTaskStarted = false;
	StartTask(armControl);
	//Starts arm stuff

	while (true) {
		//Forwards/Backwards
		motor[driveMotorRight]  = vexRT[Ch3] - vexRT[Ch1];
		motor[driveMotorLeft] = vexRT[Ch3] + vexRT[Ch1];
		//Strafe
		motor[driveMotorCenter] = vexRT[Ch4];


		//Arm
		if (!(vexRT[Btn6D] && vexRT[Btn6U])) {
			//Nothing pressed
			if (!armTaskStarted) {
				//If task is not started, start it
				armTaskStarted = true;
				//Sets speed to zero so it is not as 127/-127 at first
				setArmSpeed(0,0);
				startTask(stabilizeArm);
			}
		}

		else {
			//Button is pressed
			if (armTaskStarted) {
				//End task if arm task is working
				EndTask(stabilizeArm);
				armTaskStarted = false;
			}
			//If up button pressed
			if (vexRT[Btn6U]) {
				setArmSpeed(armSpeed, 0);
			}
			else {
				//This must be if the other (6D) button is pressed
				setArmSpeed(-armSpeed, 0)
			}
		}


		if (vexRT[Btn8D]) {
			setArmSpeed(0,0);
			//PANIC BUTTON!! Stops the arm from doint its stuff 
		}


		//Wrist
		if (vexRT[Btn5U]) {
			setWristSpeed(wristSpeed, 0);
		}
		else if (vexRT[Btn5D]) {
			setWristSpeed(-wristSpeed, 0);
		}
		else {
			setWristSpeed(0,0);
		}

	}

}
