#pragma config(Motor,  port1,           frontMotor,         tmotorVex269, openLoop)
#pragma config(Motor,  port2,           backMotor,          tmotorVex269, openLoop)
#pragma config(Motor,  port3,           leftMotor,          tmotorVex269, openLoop)
#pragma config(Motor,  port4,           rightMotor,         tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true) {
		motor[leftMotor] = vexRT[Ch2] + vexRT[Ch4];
		motor[rightMotor] = -vexRT[Ch2] + vexRT[Ch4];
		motor[frontMotor] = vexRT[Ch1] + vexRT[Ch4];
		motor[backMotor] = -vexRT[Ch1] + vexRT[Ch4];
		}
}
