#pragma config(Motor,  port2,           DriveFL,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           DriveFR,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           DriveBL,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           DriveBR,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Did you know that the greek question mark is: ;
//Blank space for comparison. Semi-colon:       ;
//;; Which one is the semicolon? Give some code to a guy you hate and ask them to debug


short absolute(short blabla) {
	if (blabla < 0) {
		blabla = blabla * -1;
	}
	return blabla;
}

task arm() {
	//My spagehetti code
	char armOn = 0; //Is the arm ready to fire?
	char armed = 0; //Ready to fire
	//button1 and button2 are two button switches
	while (true) {
		if (vexRT[Btn8D] == 1 && armed == 0) {//If button pressed and arm is not armed
			armOn = 1;
		}
		if (armOn) {
			motor[armMotor] = 127;//Or -127
		}
		if ((sensor[sensor1] || sensor[sensor2]) == 0) {// If neither are pressed
			armOn = 1; //Continue to power the motor
		}
		else if (sensor[sensor1] ^ sensor[sensor2]) {//^ is exclusive OR
			armed = 1;
			armOn = 0;
		}
		if (vexRT[Btn8D] && armed) {
			while (sensor[sensor1] ^ sensor[sensor2]) {//While only one is pressed
				motor[armMotor] = 127;
			}
			wait1Msec(500); //After launch, wait half a second
		}

	}

}



task main() {
	StartTask(arm);
	while (true) {
		short channelOne   = ((1 / 127) * vexRT[Ch1] * absolute(vexRT[Ch1]));
		short channelThree = ((1 / 127) * vexRT[Ch3] * absolute(vexRT[Ch3]));
		short channelFour = ((1 / 127) * vexRT[Ch4] * absolute(vexRT[Ch4]))
		motor[driveFL] =  channelThree + channelFour + channelOne;
		motor[driveFR] = -channelThree + channelFour + channelOne;
		motor[driveBL] =  channelThree - channelFour + channelOne;
		motor[driveBR] = -channelThree - channelFour + channelOne;
	}
}


//Have two button switches on top of each other (like a camera)
//When one is pushed down, that means that the arm is primed
//When two are pushed down, it will mean that the arm is just about to fire
