#pragma config(Motor,  port1,           driveLeft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveRight,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		motor[driveLeft] = vexRT[Ch3];
		motor[driveRight] = vexRT[Ch2];
	}
}
