#pragma config(Motor,  port1,           lDrive,        tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port10,          rDrive,        tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
char switcher = 1;


void change(char value);

task main(){

	while(switcher) {
		motor(lDrive) = vexRT(Ch2) + vexRT(Ch1);
		motor(rDrive) = vexRT(Ch2) - vexRT(Ch1);
		change(0);
	}

	while(switcher == 0) {
		motor(lDrive) = vexRT(Ch3);
		motor(rDrive) = vexRT(Ch2);
		change(1);
	}
}


void change(char value){
	if(vexRT[Btn8D]) {
		switcher = value;
	}
}
