#pragma config(Motor,  port1,           BL,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           strafe,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rotateArm,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           poke,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armR,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BR,            tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Center wheels will use Y-cable


const int pokeSpeed = 60;
const int minDriveSpeed = 5;
const int clawSpeed = 60;
const int rotateSpeed = 20;
const int armSpeed = 60;
int correctJoystick(int min, int val) {
	//Joystick not always centered at 0. If below certain threshold, returns 0
	if (-min < val || val < min) {
		return 0;
	}
	else {
		return val;
	}
}

void setMotorSpeed(int x, int rotate, int y) {
	motor[BL] = motor[FL] = correctJoystick(minDriveSpeed, x - rotate);
	motor[BR] = motor[FR] = correctJoystick(minDriveSpeed, x + rotate);
	motor[strafe] = correctJoystick(minDriveSpeed, y);
}

task main() {
	while(true) {
		setMotorSpeed(vexRT[Ch4], vexRT[Ch1], vexRT[Ch3]);

        //Poke
        if (vexRT[Btn8D]) {
            motor[poke] = -pokeSpeed;
        }
        else if (vexRT[Btn8U]) {
            motor[poke] = pokeSpeed;
        }
        else {
            motor[poke] = 0;
        }

        //Rotate Arm
        if (vexRT[Btn7D]) {
            motor[rotateArm] = -rotateSpeed;
        }
        else if (vexRT[Btn7U]) {
            motor[rotateArm] = rotateSpeed;
        }
        else {
            motor[rotateArm] = 0;
        }

        //Arm
        if (vexRT[Btn6D]) {
            motor[armL] = motor[armR] = -armSpeed;
        }
        else if (vexRT[Btn5D]) {
            motor[armL] = motor[armR] = armSpeed;
        }
        else {
            motor[armL] = motor[armR] = 0;
        }


        //Claw
        if (vexRT[Btn5U]) {
        	motor[claw] = -clawSpeed;
        }
        else if (vexRT[Btn5D]) {
        	motor[claw] = clawSpeed;
        }
        else {
        	motor[claw] = 0;
				}

		wait1Msec(1);
	}
}
